from dotenv import load_dotenv
load_dotenv()
from apscheduler.schedulers.background import BackgroundScheduler
from ai_generator.generator import generate_blog_post
import feedparser
import datetime
import os
import random

TRENDING_KEYWORDS = [
    "summer fashion trends 2025",
    "best travel destinations 2025",
    "healthy meal prep ideas",
    "how to start investing",
    "fitness challenge for beginners",
    "home workout routines",
    "latest iPhone rumors",
    "morning routine tips",
    "side hustle ideas",
    "2025 college graduation gifts",
    "budget travel tips",
    "how to save money fast",
    "relationship advice for couples",
    "new Netflix releases",
    "mental health awareness month",
    "TikTok productivity hacks",
    "remote job opportunities",
    "spring cleaning checklist",
    "easy weeknight dinners",
    "how to improve sleep quality",
    "romantasy book recommendations",
    "eco-friendly gadgets 2025",
    "digital product passports",
    "bouclé bed decor trend",
    "CBG gummies benefits",
    "Claude AI chatbot",
    "AI vocal remover tools",
    "Claude AI vs GPT-5",
    "AI affiliate marketing",
    "SaaS ideas with AI",
    "AI for SEO content",
    "lavender girl aesthetic",
    "sardine fashion trend",
    "cowboy-themed travel experiences",
    "literary-inspired travel",
    "astrocartography travel",
    "extended honeymoons",
    "women's history travel",
    "gastronomic adventures",
    "accessible adventure travel",
    "wellness travel 2025",
    "rural upskilling trips",
    "luxury train travel experiences",
    "night tourism trends",
    "sleepmaxxing for wellness",
    "pet ownership trends",
    "thrifting trends 2025",
    "castlecore fashion",
    "cherry-coded beauty trend",
    "goddesscore accessories",
    "fisherman chic style",
    "aura beauty makeup",
    "sea witchery aesthetics",
    "moto boho fashion",
    "mental health apps for teens",
    "dumb phones resurgence",
    "online shopping habits of Gen Z",
    "anime popularity among teens",
    "sustainable living tips",
    "digital detox methods",
    "budget-friendly home decor",
    "DIY crafts for beginners",
    "plant-based diet benefits",
    "minimalist lifestyle guide",
    "remote work productivity tools",
    "virtual reality gaming trends",
    "cryptocurrency investment basics",
    "online education platforms",
    "language learning apps",
    "podcast recommendations 2025",
    "book club ideas",
    "self-care routines",
    "mindfulness meditation techniques",
    "urban gardening tips",
    "zero waste lifestyle",
    "digital art tutorials",
    "photography tips for beginners",
    "freelancing platforms comparison",
    "online course creation guide",
    "personal finance management apps",
    "stock market investing for beginners",
    "budgeting tips for students",
    "career change advice",
    "resume writing tips",
    "job interview preparation",
    "networking strategies",
    "public speaking techniques",
    "time management skills",
    "goal setting methods",
    "productivity hacks",
    "habit tracking tools",
    "journaling prompts",
    "creative writing exercises",
    "short story ideas",
    "poetry writing tips",
    "novel writing guide",
    "screenwriting basics",
    "storyboarding techniques",
    "video editing software reviews",
    "vlogging equipment recommendations",
    "live streaming tips",
    "social media marketing strategies",
    "email marketing best practices",
    "content creation ideas",
    "graphic design tools",
    "website building platforms",
    "e-commerce business models",
    "dropshipping guide",
    "print on demand services",
    "affiliate marketing programs",
    "influencer marketing trends",
    "branding strategies",
    "logo design inspiration",
    "color theory basics",
    "typography tips",
    "UX/UI design principles",
    "app development tutorials",
    "coding bootcamps",
    "programming languages to learn",
    "tech industry job roles",
    "cybersecurity awareness",
    "data privacy tips",
    "cloud computing services",
    "artificial intelligence applications",
    "machine learning projects",
    "blockchain technology explained",
    "Internet of Things devices",
    "smart home gadgets",
    "wearable technology trends",
    "electric vehicles overview",
    "renewable energy sources",
    "climate change solutions",
    "environmental conservation efforts",
    "wildlife protection initiatives",
    "sustainable fashion brands",
    "ethical consumerism practices",
    "fair trade products",
    "organic farming methods",
    "local food movements",
    "farmers market shopping tips",
    "seasonal recipes",
    "cooking techniques for beginners",
    "baking tutorials",
    "meal planning strategies",
    "grocery shopping on a budget",
    "kitchen organization hacks",
    "home cleaning schedules",
    "decluttering tips",
    "interior design trends",
    "furniture arrangement ideas",
    "lighting design concepts",
    "color palette selection",
    "wall art inspiration",
    "DIY home improvement projects",
    "toolbox essentials",
    "safety tips for home repairs",
    "plumbing basics",
    "electrical wiring guidelines",
    "garden landscaping ideas",
    "outdoor furniture selection",
    "patio decoration tips",
    "fence installation guide",
    "lawn care routines",
    "composting methods",
    "rainwater harvesting systems",
    "solar panel installation",
    "energy-efficient appliances",
    "home insulation techniques",
    "smart thermostat benefits",
    "security system options",
    "fire safety measures",
    "emergency preparedness plans",
    "first aid kit essentials",
    "pet care tips",
    "dog training techniques",
    "cat behavior understanding",
    "pet nutrition advice",
    "veterinary care guidelines",
    "pet grooming tutorials",
    "pet-friendly travel tips",
    "adopting rescue animals",
    "pet insurance options",
    "animal welfare organizations",
    "wildlife conservation efforts",
    "bird watching guides",
    "aquarium maintenance tips",
    "reptile care basics",
    "insect identification resources",
    "nature photography techniques",
    "hiking trail recommendations",
    "camping gear checklists",
    "survival skills training",
    "outdoor cooking recipes",
    "stargazing tips",
    "constellation maps",
    "astronomy news updates",
    "space exploration missions",
    "NASA discoveries",
    "telescope buying guides",
    "astrophotography tutorials",
    "science fiction book lists",
    "sci-fi movie recommendations",
    "fantasy novel series",
    "comic book collections",
    "graphic novel reviews",
    "manga reading order",
    "anime series rankings",
    "cosplay costume ideas",
    "convention attendance tips",
    "fan art creation techniques",
    "character design inspiration",
    "storytelling in games",
    "game development tools",
    "indie game showcases",
    "esports tournament schedules",
    "streaming platform comparisons",
    "gaming PC build guides",
    "console gaming news",
    "mobile game recommendations",
    "virtual reality experiences",
    "augmented reality applications",
    "mixed reality innovations",
    "technology news updates",
    "startup success stories",
    "entrepreneurship advice",
    "business plan templates",
    "marketing campaign examples",
    "customer service strategies",
    "sales techniques",
    "negotiation skills",
    "leadership development programs",
    "team building activities",
    "employee engagement ideas",
    "remote work policies",
    "work-life balance tips",
    "career advancement opportunities",
    "professional networking events",
    "industry conference schedules",
    "certification courses",
    "online learning platforms",
    "educational podcasts",
    "language exchange programs",
    "study abroad opportunities",
    "student loan repayment plans",
    "scholarship application tips",
    "college admission requirements",
    "exam preparation strategies",
    "note-taking methods",
    "study group organization",
    "academic writing guidelines",
    "research paper formatting",
    "citation style references",
    "plagiarism prevention tools",
    "online library resources",
    "educational technology tools",
    "virtual classroom platforms",
    "homeschooling curricula",
    "parenting advice columns",
    "child development milestones",
    "early childhood education activities",
    "teen mental health resources",
    "family bonding activities",
    "relationship counseling services",
    "marriage advice forums",
    "divorce support groups",
    "grief counseling techniques",
    "self-help book recommendations",
    "personal growth workshops",
    "life coaching sessions",
    "motivational speaker events",
    "goal achievement strategies",
    "habit formation methods",
    "mindset shift exercises",
    "positive affirmations list",
    "gratitude journaling prompts",
    "vision board creation",
    "meditation practices",
    "yoga pose tutorials",
    "breathing exercises",
    "stress management techniques",
    "anxiety relief methods",
    "depression coping strategies",
    "therapy options",
    "mental health hotlines",
    "support group directories",
    "wellness retreat locations",
    "spa treatment packages",
    "massage therapy benefits",
    "aromatherapy uses",
    "essential oil blends",
    "natural skincare routines",
    "organic beauty products",
    "makeup application tips",
    "hair care regimens",
    "nail art designs",
    "fashion styling advice",
    "wardrobe organization hacks",
    "clothing subscription boxes",
    "thrift shopping tips",
    "sustainable fashion brands",
    "ethical clothing materials",
    "size-inclusive fashion lines",
    "seasonal outfit ideas",
    "accessory pairing suggestions",
    "shoe care instructions",
    "jewelry maintenance tips",
    "watch buying guides",
    "handbag selection criteria",
    "belt styling options",
    "hat wearing etiquette",
    "scarf tying methods",
    "glove sizing charts",
    "sunglasses frame shapes",
    "eyewear prescription updates",
    "contact lens care",
    "eye health checkups",
    "vision correction procedures",
    "hearing aid technologies",
    "audiology services",
    "dental hygiene practices",
    "orthodontic treatment plans",
    "cosmetic dentistry options",
    "skin cancer prevention",
    "dermatology appointments",
    "allergy management strategies",
    "immunization schedules",
    "vaccination information",
    "primary care physician selection",
    "specialist referral processes",
    "health insurance plans",
]

GENERATED_POSTS_DIR = 'generated_posts'
os.makedirs(GENERATED_POSTS_DIR, exist_ok=True)

def generate_and_save_daily_post():
    keyword = random.choice(TRENDING_KEYWORDS)
    markdown_content = generate_blog_post(keyword)
    today = datetime.datetime.now().strftime('%Y-%m-%d')
    filename = f"{GENERATED_POSTS_DIR}/blog_{keyword.replace(' ', '_')}_{today}.md"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    print(f"[Scheduler] Generated daily blog post for '{keyword}' at {filename}")

scheduler = BackgroundScheduler(daemon=True)
scheduler.add_job(generate_and_save_daily_post, 'cron', hour=0, minute=0)
scheduler.start()